#
# refind.conf
# Configuration file for the rEFInd boot menu
#

timeout 0
#log_level 1
use_nvram false
scanfor manual

hideui label, singleuser, safemode, hwtest, arrows, hints, editor, badges
showtools reboot shutdown

default_selection "Arch"

menuentry "Arch" {
	icon /EFI/refind/theme/icons/os_arch.png
	loader /vmlinuz-linux
	initrd /initramfs-linux.img
	options "root=UUID=0a689228-450b-4300-a98d-e59c980327d0 rw rootflags=subvol=@ zswap.enabled=0 rootfstype=btrfs loglevel=3 quiet"
}

menuentry "Arch Lts" {
	icon /EFI/refind/theme/icons/os_arch_lts.png
	loader /vmlinuz-linux-lts
	initrd /initramfs-linux-lts.img
	options "root=UUID=0a689228-450b-4300-a98d-e59c980327d0 rw rootflags=subvol=@ zswap.enabled=0 rootfstype=btrfs loglevel=3 quiet"
}

menuentry "Windows 10" {
	icon /EFI/refind/theme/icons/os_win.png
	loader /EFI/Microsoft/Boot/bootmgfw.efi
}

include theme/theme.conf