[env]
SHELL = "/bin/zsh"

[terminal]
shell = "/bin/zsh"

[window]
padding = { x = 10, y = 10 }
opacity = 0.8

[font]
normal = { family = "FiraCode NerdFont Mono", style = "Regular" }

[colors]
primary = { background = "#222831", foreground = "#ffd369" }
