# Polkit
exec-once = systemctl --user start hyprpolkitagent

### Theming
# exec = gsettings set org.gnome.desktop.interface gtk-theme "Pax-GTK"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps


#------------#
# auto start #
#------------#
exec-once = USE_LAYER_SHELL=0 vicinae server
exec-once = quickshell
exec-once = swww-daemon
exec-once = waypaper --random

# Auto-start Alacritty in a named special workspace
exec-once = [workspace special:terminal silent] alacritty
