# Polkit
exec-once = systemctl --user start hyprpolkitagent

### Theming
# exec = gsettings set org.gnome.desktop.interface gtk-theme "Pax-GTK"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

# Vicinae Server
exec-once = vicinae server

# Quickshell
exec-once = quickshell

# Wallpaper
# exec-once = swww-daemon
# exec-once = waypaper --random

# Auto-start Alacritty in a named special workspace
exec-once = [workspace special:terminal silent] alacritty

# Populate "Open With" menu in dolphin
exec-once = kbuildsycoca6 --noincremental

# Plugins
exec-once = hyprctl plugin load /mnt/hdd_01/data/Dev/repos/hypr-bevel-bars/hypr-bevel-bars.so
