plugin {
    hyprbevelbars {
        accent_color_follows_border = false
        bar_precedence_over_border = false
        bar_height = 32
        border_thickness = 2
        chamfer = 16
        chamfer_small = 10
        padding = 0
    }
}
