windowrule {
    name = games
    match:class = gamescope

    workspace = name:game
    opacity = 1 1 override
}

windowrule {
    name = vivaldi
    match:title = (.*)(- YouTube - Vivaldi)

    opacity = 1 1 override
}

windowrule {
    name = jetbrains
    match:class = (jetbrains-)(.*)

    no_initial_focus = on
    float = 1
}

windowrule {
    name = jetbrains-toolbox
    match:class = jetbrains-toolbox

    move = 1933 21
}

windowrule {
    name = comms
    match:class = discord|org.telegram.desktop

    workspace = special:communications
}

windowrule {
    name = vicinae
    match:class = vicinae

    stay_focused = on
}