workspace = name:game, monitor:DP-2, decorate:false

# Special Workspace: Terminal
workspace = special:terminal, on-created-empty:alacritty
workspace = special:terminal, gapsout:256

# Special Workspace Communications
workspace = special:communications, on-created-empty:$HOME/.config/scripts/start-communications.sh
workspace = special:communications, gapsout:128